### ISSUE TITLE
Supported generative tasks

### ISSUE THREAD

**Issue by taehyunzzz** [allenai/OLMoE#13]
First of all, thank you for sharing your work.
I was wondering which generative tasks are supported by the open-sourced pretrained weights?
I want to test them out using LLM Harness.
Also, to use in LLM Harness generative tasks, which one of the base/Instruct/SFT versions should I use?

Taehyun

**Comment by Muennighoff** [comment]
If you refer to https://github.com/EleutherAI/lm-evaluation-harness then pretty much any task should be supported I think? It may not perform as well on non-English task.

I think you'd want to use the base model there.
