### ISSUE TITLE
Dropout Regularization in expert modules

### ISSUE THREAD

**Issue by taehyunzzz** [allenai/OLMoE#14]
Previous works like switch transformers say they use higher dropout rate in the expert modules.
Does OLMoE apply higher expert dropouts (e.g., 0.3 or 0.4) when training?

Taehyun

**Comment by Muennighoff** [comment]
we used no dropout; you can check the config here: https://wandb.ai/ai2-llm/olmoe/runs/rzsn9tlc/overview or here: https://github.com/allenai/OLMoE/blob/main/configs/OLMoE-1B-7B-0824.yml

**Comment by taehyunzzz** [comment]
Interesting... I am doing MoE training myself, and I find it sometimes very difficult to train MoEs to be better than non-MoE compute-equivalent counterparts (as in OLMo-1B for OLMoE-1B-7B). Have you had similar observations? Can you give me tips on make MoEs more powerful or how to present that MoEs are better than the non-MoEs?

**Comment by Muennighoff** [comment]
interesting - could definitely be worth ablating. Just didn't try it.

It should be better - you can check the MoE vs Dense plot in our paper maybe to get some insights? The configs etc for that are also open-source so you could just rerun that
