### ISSUE TITLE
Config Naming

### ISSUE THREAD

**Issue by mchorton** [allenai/OLMoE#16]
The README says: "`configs/OLMoE-1B-7B-0924.yml` was used for the pretraining of `OLMoE-1B-7B-0924`"

That config doesn't exist. However, there is a `configs/OLMoE-1B-7B-0824.yml` (note the "08" instead of "09").

Is the config misnamed, or is the config missing?

**Comment by Muennighoff** [comment]
Sorry it is misnamed & i've renamed the config, thanks!
