### ISSUE TITLE
Can't open link in README Adaptation “Clone this open-instruct branch & follow its setup instructions.”

### ISSUE THREAD

**Issue by He-JYang** [allenai/OLMoE#19]
It seems like you delete this branch
https://github.com/allenai/open-instruct/tree/olmoe-sft

Where can I get the adaptation  setup instructions？

**Comment by He-JYang** [comment]
![image](https://github.com/user-attachments/assets/8325da48-bc9b-4841-a211-58ba7a7fad0d)

**Comment by jacob-morrison** [comment]
Hello! Sorry about that, we merged that branch into main and forgot to update the documentation :) You should be able to just clone from `main` instead. There's a chance you'll have to upgrade the transformers version as well, so if you run into any issues try running `pip install --upgrade transformers`.
